global:
  domain: argocd.chateautechlab.org

server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: "argocd.chateautechlab.org"
    tls: false
    extraTls:
    - hosts:
      - argocd.chateautechlab.org
      secretName: argocd-tls
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS


