
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-cert
  namespace: harbor
spec:
  dnsNames:
    - harbor.chateautechlab.org
  secretName: harbor-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  dnsNames:
    - argocd.chateautechlab.org
  secretName: argocd-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: keycloak
spec:
  secretName: keycloak-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  #commonName: keycloak.chateautechlab.com
  commonName: keycloak.chateautechlab.org
  dnsNames:
    #- keycloak.chateautechlab.com
    - keycloak.chateautechlab.org
    
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment

#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: keycloak-cert
#  namespace: keycloak
#spec:
#  dnsNames:
#    - keycloak.chateautechlab.com
#  secretName: keycloak-tls
#  issuerRef:
#    name: letsencrypt-issuer
#    kind: ClusterIssuer
    